// iGreenApp/src/components/Login.tsx
import React, { useState } from 'react';
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { User, Lock, ArrowRight, Loader2 } from 'lucide-react';
import { Card, CardContent, CardFooter, CardHeader } from "./ui/card";
import { toast } from "sonner@2.0.3";
import logoImage from "figma:asset/e827750074831b7c0b1fd927cc5b318bf0bb80ab.png";
import { api } from '../lib/api';

interface LoginProps {
  onLogin: () => void;
}

export function Login({ onLogin }: LoginProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [account, setAccount] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!account || !password) {
      toast.error("请输入账号和密码");
      return;
    }

    setIsLoading(true);

    try {
      const data = await api.login(account, password);
      toast.success("登录成功");
      onLogin();
    } catch (error: any) {
      console.error("Login failed:", error);
      toast.error(error.message || "登录失败，请检查账号和密码");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-teal-50 flex flex-col items-center justify-center p-4 relative overflow-hidden">
      
      {/* Background Decoration */}
      <div className="absolute top-0 left-0 w-full h-64 bg-teal-600 z-0"></div>
      <div className="absolute top-40 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-white/10 rounded-full blur-3xl z-0 pointer-events-none"></div>

      <div className="w-full max-w-md z-10">
        
        <div className="flex flex-col items-center mb-8">
          <div className="w-20 h-20 bg-white rounded-2xl flex items-center justify-center mb-4 shadow-lg shadow-teal-900/10 p-2">
            <img src={logoImage} alt="iGreen+ Logo" className="w-full h-full object-contain" />
          </div>
          <h1 className="text-3xl font-bold text-teal-900 tracking-tight">iGreen+</h1>
        </div>

        <Card className="border-none shadow-xl">
          <CardHeader className="space-y-1 pb-2">
            <h2 className="text-2xl font-bold text-center text-slate-900">Sign in to your account</h2>
            <p className="text-sm text-slate-500 text-center">Enter your account and password</p>
          </CardHeader>
          <CardContent className="space-y-4 pt-4">
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="account">Account</Label>
                <div className="relative">
                  <User className="absolute left-3 top-3 h-4 w-4 text-slate-400" />
                  <Input 
                    id="account" 
                    placeholder="Username or Account ID" 
                    type="text" 
                    className="pl-9 focus-visible:ring-teal-600"
                    value={account}
                    onChange={(e) => setAccount(e.target.value)}
                    required
                  />
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label htmlFor="password">Password</Label>
                </div>
                <div className="relative">
                  <Lock className="absolute left-3 top-3 h-4 w-4 text-slate-400" />
                  <Input 
                    id="password" 
                    type="password" 
                    className="pl-9 focus-visible:ring-teal-600"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                  />
                </div>
              </div>
              <Button 
                type="submit" 
                className="w-full bg-teal-600 hover:bg-teal-700 h-11 text-base"
                disabled={isLoading}
              >
                {isLoading ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Signing in...
                  </>
                ) : (
                  <>
                    Sign In
                    <ArrowRight className="w-4 h-4 ml-2" />
                  </>
                )}
              </Button>
            </form>
          </CardContent>
          <CardFooter className="flex flex-col space-y-4 bg-slate-50/50 border-t p-6">
            <div className="text-center text-xs text-slate-500">
              By clicking continue, you agree to our <a href="#" className="underline hover:text-slate-900">Terms of Service</a> and <a href="#" className="underline hover:text-slate-900">Privacy Policy</a>.
            </div>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}

// igreen-uniapp/src/pages/login/index.vue
<template>
  <view class="login-container">
    <view class="bg-decoration"></view>
    <view class="bg-blur"></view>

    <view class="login-card">
      <view class="logo-section">
        <view class="logo-container">
          <image class="logo-image" src="/static/logo.png" mode="aspectFit" />
        </view>
        <text class="app-title">iGreen+</text>
      </view>

      <view class="form-section">
        <text class="form-title">Sign in to your account</text>
        <text class="form-subtitle">Enter your account and password</text>

        <view class="input-group">
          <text class="input-label">Account</text>
          <view class="input-wrapper">
            <Input
              v-model="account"
              type="text"
              placeholder="Username or Account ID"
            >
              <template #prefix>
                <text class="input-icon">👤</text>
              </template>
            </Input>
          </view>
        </view>

        <view class="input-group">
          <text class="input-label">Password</text>
          <view class="input-wrapper">
            <Input
              v-model="password"
              type="password"
              placeholder="Enter your password"
            >
              <template #prefix>
                <text class="input-icon">🔒</text>
              </template>
            </Input>
          </view>
        </view>

        <Button class="submit-btn" :loading="isLoading" @click="handleLogin">
          {{ isLoading ? "Signing in..." : "Sign In" }}
        </Button>
      </view>

      <view class="footer-section">
        <text class="footer-text">
          By clicking continue, you agree to our Terms of Service and Privacy
          Policy.
        </text>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { setUser, setAuthToken } from "@/store";
import { api } from "@/utils/api";
import { Button, Input } from "@/components/ui";

const emit = defineEmits<{
  (e: "login"): void;
}>();

const account = ref<string>("");
const password = ref<string>("");
const isLoading = ref(false);

async function handleLogin() {
  if (!account.value || !password.value) {
    uni.showToast({
      title: "Please enter credentials",
      icon: "none",
    });
    return;
  }

  isLoading.value = true;

  try {
    const result = await api.login(account.value, password.value);
    setAuthToken(result.access_token);
    setUser(result.user);

    uni.showToast({
      title: "Welcome!",
      icon: "success",
    });

    setTimeout(() => {
      emit("login");
    }, 500);
  } catch (error: any) {
    console.error("Login error:", error);
    uni.showToast({
      title: error.message || "Login failed",
      icon: "none",
    });
  } finally {
    isLoading.value = false;
  }
}
</script>

<style lang="scss" scoped>
@import "@/uni.scss";

.login-container {
  min-height: 100vh;
  background: $teal-50; // teal-50 - matches iGreenApp
  display: flex;
  align-items: center;
  justify-content: center;
  padding: $spacing-4;
  position: relative;
  overflow: hidden;
}

.bg-decoration {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 256px; // ~40% of viewport height
  background: $teal-600; // teal-600 - matches iGreenApp
  z-index: 0;
}

.bg-blur {
  position: absolute;
  top: 160px;
  left: 50%;
  transform: translateX(-50%);
  width: 800px;
  height: 800px;
  background: rgba(255, 255, 255, 0.1);
  border-radius: $radius-full;
  filter: blur(64px);
  z-index: 0;
  pointer-events: none;
}

.login-card {
  width: 100%;
  max-width: 420px;
  background: $card;
  border-radius: $radius-xl;
  box-shadow:
    0 20px 25px -5px rgba(0, 0, 0, 0.1),
    0 8px 10px -6px rgba(0, 0, 0, 0.1); // shadow-xl - matches iGreenApp
  padding: $spacing-6; // p-6 (24px) - matches iGreenApp Card padding
  padding-top: $spacing-6; // pt-6 - matches iGreenApp
  z-index: 1;
  border: none;
}

.logo-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-bottom: $spacing-6; // mb-6 (24px) - matches iGreenApp card-header gap
}

.form-section {
  padding-top: $spacing-4; // pt-4 - matches iGreenApp
  padding-bottom: 0; // Remove default padding
}

.input-group {
  margin-bottom: $spacing-4; // space-y-4 - matches iGreenApp
}

.footer-section {
  padding: $spacing-6; // p-6
  margin: 0 -#{$spacing-6}; //抵消 card padding
  margin-top: $spacing-4;
  background: rgba($gray-50, 0.5); // bg-slate-50/50
  border-top: 1px solid $border;
}

.logo-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-bottom: $spacing-8;
}

.logo-container {
  width: 80px;
  height: 80px;
  background: $white;
  border-radius: $radius-xl;
  box-shadow: 0 10px 25px -5px rgba(19, 78, 74, 0.1); // teal-900 with opacity
  display: flex;
  align-items: center;
  justify-content: center;
  padding: $spacing-3;
  margin-bottom: $spacing-4;
}

.logo-image {
  width: 100%;
  height: 100%;
}

.app-title {
  font-size: 30px;
  font-weight: $font-weight-bold;
  color: $teal-900; // teal-900 - matches iGreenApp
  letter-spacing: -0.5px;
}

.form-section {
  margin-bottom: $spacing-4;
}

.form-title {
  font-size: $text-2xl;
  font-weight: $font-weight-bold;
  color: $gray-900; // slate-900
  text-align: center;
  display: block;
  margin-bottom: $spacing-1;
}

.form-subtitle {
  font-size: $text-sm;
  color: $gray-500; // slate-500
  text-align: center;
  display: block;
  margin-bottom: $spacing-6;
  font-weight: $font-weight-normal;
}

.input-group {
  margin-bottom: $spacing-4;
}

.input-label {
  font-size: $text-sm;
  font-weight: $font-weight-medium;
  color: $gray-700; // slate-700
  display: block;
  margin-bottom: $spacing-2;
}

.input-wrapper {
  width: 100%; // Full width - fills the row
  position: relative;
  align-items: center;
}

.input-icon {
  font-size: 16px;
  color: $gray-400; // slate-400
}

.submit-btn {
  width: 100%;
  height: 44px;
  margin-top: $spacing-6;
  background: $teal-600; // teal-600 - matches iGreenApp
  color: $white;
  border-radius: $radius-md;
  font-size: $text-base;
  font-weight: $font-weight-medium;

  &:hover {
    background: $teal-700; // teal-700
  }

  &:active {
    background: $teal-700;
  }
}

.footer-section {
  padding: $spacing-6;
  margin: 0 -#{$spacing-8};
  margin-top: $spacing-4;
  background: rgba($gray-50, 0.5);
  border-top: 1px solid $border;
  border-bottom-left-radius: $radius-xl;
  border-bottom-right-radius: $radius-xl;
}

.footer-text {
  font-size: 12px;
  color: $gray-500; // slate-500
  text-align: center;
  display: block;
  line-height: 1.5;
}
</style>
